name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodando um teste simples
        run: echo "CI funcionando com sucesso!"

      - name: Notificar no Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ CI executado com sucesso no projeto!\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
